[package]
name = "pod_exec"
version = "0.1.0"
edition = "2021"

[dependencies]
common.workspace = true
logger.workspace = true
kube.workspace = true
serde = { version = "1.0", features = ["derive"] }
