apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
spec:
  containers:
    - name: ubuntu
      image: ubuntu:22.04
      command: ["/bin/sh", "-c", "tail -f /dev/null"]
      resources:
        limits:
          memory: "128Mi"
          cpu: "100m"
